// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"shopping/thrift_client/user/controller"
)

// Injectors from wire.go:

func InitializeUserController() (*controller.UserController, error) {
	userController := &controller.UserController{}
	return userController, nil
}
