// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user_service

import (
	"shopping/user_service/controller"
	"shopping/user_service/manager"
	"shopping/user_service/po"
	"shopping/user_service/repository"
	"shopping/user_service/server/handler"
	"shopping/user_service/service"
)

// Injectors from wire.go:

func InitializeUserController() (*controller.UserController, error) {
	userLoginPO := po.NewUserLoginPO()
	userInfoPO := po.NewUserInfoPO()
	userRepository := repository.NewUserRepository(userLoginPO, userInfoPO)
	userService := service.NewUserService(userRepository)
	userManager := manager.NewUserManager(userService)
	userController := &controller.UserController{
		UserManager: userManager,
	}
	return userController, nil
}

func InitializeUserHandler() (*handler.UserHandler, error) {
	userLoginPO := po.NewUserLoginPO()
	userInfoPO := po.NewUserInfoPO()
	userRepository := repository.NewUserRepository(userLoginPO, userInfoPO)
	userService := service.NewUserService(userRepository)
	userManager := manager.NewUserManager(userService)
	userHandler := &handler.UserHandler{
		UserManager: userManager,
	}
	return userHandler, nil
}
