// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package product_service

import (
	"shopping/product_service/controller"
	"shopping/product_service/manager"
	"shopping/product_service/po"
	"shopping/product_service/repository"
	"shopping/product_service/server/handler"
	"shopping/product_service/service"
)

// Injectors from wire.go:

func InitializeProductController() (*controller.ProductController, error) {
	productPO := po.NewProductPO()
	productStockPO := po.NewProductStockPO()
	productRepository := repository.NewProductRepository(productPO, productStockPO)
	productService := service.NewProductService(productRepository)
	productManager := manager.NewProductManager(productService)
	productController := &controller.ProductController{
		ProductManager: productManager,
	}
	return productController, nil
}

func InitializeProductHandler() (*handler.ProductServiceImpl, error) {
	productPO := po.NewProductPO()
	productStockPO := po.NewProductStockPO()
	productRepository := repository.NewProductRepository(productPO, productStockPO)
	productService := service.NewProductService(productRepository)
	productManager := manager.NewProductManager(productService)
	productServiceImpl := &handler.ProductServiceImpl{
		ProductManager: productManager,
	}
	return productServiceImpl, nil
}
