// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package product

import (
	"context"
	"fmt"
)

type ProductRequest struct {
	Id          *int64   `thrift:"id,1,optional" frugal:"1,optional,i64" json:"id,omitempty"`
	ProductName *string  `thrift:"productName,2,optional" frugal:"2,optional,string" json:"productName,omitempty"`
	Category    *string  `thrift:"category,3,optional" frugal:"3,optional,string" json:"category,omitempty"`
	Price       *float64 `thrift:"price,4,optional" frugal:"4,optional,double" json:"price,omitempty"`
	Description *string  `thrift:"description,5,optional" frugal:"5,optional,string" json:"description,omitempty"`
	Status      *int8    `thrift:"status,6,optional" frugal:"6,optional,i8" json:"status,omitempty"`
	CreateTime  *string  `thrift:"createTime,7,optional" frugal:"7,optional,string" json:"createTime,omitempty"`
}

func NewProductRequest() *ProductRequest {
	return &ProductRequest{}
}

func (p *ProductRequest) InitDefault() {
}

var ProductRequest_Id_DEFAULT int64

func (p *ProductRequest) GetId() (v int64) {
	if !p.IsSetId() {
		return ProductRequest_Id_DEFAULT
	}
	return *p.Id
}

var ProductRequest_ProductName_DEFAULT string

func (p *ProductRequest) GetProductName() (v string) {
	if !p.IsSetProductName() {
		return ProductRequest_ProductName_DEFAULT
	}
	return *p.ProductName
}

var ProductRequest_Category_DEFAULT string

func (p *ProductRequest) GetCategory() (v string) {
	if !p.IsSetCategory() {
		return ProductRequest_Category_DEFAULT
	}
	return *p.Category
}

var ProductRequest_Price_DEFAULT float64

func (p *ProductRequest) GetPrice() (v float64) {
	if !p.IsSetPrice() {
		return ProductRequest_Price_DEFAULT
	}
	return *p.Price
}

var ProductRequest_Description_DEFAULT string

func (p *ProductRequest) GetDescription() (v string) {
	if !p.IsSetDescription() {
		return ProductRequest_Description_DEFAULT
	}
	return *p.Description
}

var ProductRequest_Status_DEFAULT int8

func (p *ProductRequest) GetStatus() (v int8) {
	if !p.IsSetStatus() {
		return ProductRequest_Status_DEFAULT
	}
	return *p.Status
}

var ProductRequest_CreateTime_DEFAULT string

func (p *ProductRequest) GetCreateTime() (v string) {
	if !p.IsSetCreateTime() {
		return ProductRequest_CreateTime_DEFAULT
	}
	return *p.CreateTime
}
func (p *ProductRequest) SetId(val *int64) {
	p.Id = val
}
func (p *ProductRequest) SetProductName(val *string) {
	p.ProductName = val
}
func (p *ProductRequest) SetCategory(val *string) {
	p.Category = val
}
func (p *ProductRequest) SetPrice(val *float64) {
	p.Price = val
}
func (p *ProductRequest) SetDescription(val *string) {
	p.Description = val
}
func (p *ProductRequest) SetStatus(val *int8) {
	p.Status = val
}
func (p *ProductRequest) SetCreateTime(val *string) {
	p.CreateTime = val
}

func (p *ProductRequest) IsSetId() bool {
	return p.Id != nil
}

func (p *ProductRequest) IsSetProductName() bool {
	return p.ProductName != nil
}

func (p *ProductRequest) IsSetCategory() bool {
	return p.Category != nil
}

func (p *ProductRequest) IsSetPrice() bool {
	return p.Price != nil
}

func (p *ProductRequest) IsSetDescription() bool {
	return p.Description != nil
}

func (p *ProductRequest) IsSetStatus() bool {
	return p.Status != nil
}

func (p *ProductRequest) IsSetCreateTime() bool {
	return p.CreateTime != nil
}

func (p *ProductRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductRequest(%+v)", *p)
}

var fieldIDToName_ProductRequest = map[int16]string{
	1: "id",
	2: "productName",
	3: "category",
	4: "price",
	5: "description",
	6: "status",
	7: "createTime",
}

type ProductResponse struct {
	Id          *int64   `thrift:"id,1,optional" frugal:"1,optional,i64" json:"id,omitempty"`
	ProductName *string  `thrift:"productName,2,optional" frugal:"2,optional,string" json:"productName,omitempty"`
	Category    *string  `thrift:"category,3,optional" frugal:"3,optional,string" json:"category,omitempty"`
	Price       *float64 `thrift:"price,4,optional" frugal:"4,optional,double" json:"price,omitempty"`
	Description *string  `thrift:"description,5,optional" frugal:"5,optional,string" json:"description,omitempty"`
	Status      *int8    `thrift:"status,6,optional" frugal:"6,optional,i8" json:"status,omitempty"`
	CreateTime  *string  `thrift:"createTime,7,optional" frugal:"7,optional,string" json:"createTime,omitempty"`
	StockNum    *int32   `thrift:"stockNum,8,optional" frugal:"8,optional,i32" json:"stockNum,omitempty"`
}

func NewProductResponse() *ProductResponse {
	return &ProductResponse{}
}

func (p *ProductResponse) InitDefault() {
}

var ProductResponse_Id_DEFAULT int64

func (p *ProductResponse) GetId() (v int64) {
	if !p.IsSetId() {
		return ProductResponse_Id_DEFAULT
	}
	return *p.Id
}

var ProductResponse_ProductName_DEFAULT string

func (p *ProductResponse) GetProductName() (v string) {
	if !p.IsSetProductName() {
		return ProductResponse_ProductName_DEFAULT
	}
	return *p.ProductName
}

var ProductResponse_Category_DEFAULT string

func (p *ProductResponse) GetCategory() (v string) {
	if !p.IsSetCategory() {
		return ProductResponse_Category_DEFAULT
	}
	return *p.Category
}

var ProductResponse_Price_DEFAULT float64

func (p *ProductResponse) GetPrice() (v float64) {
	if !p.IsSetPrice() {
		return ProductResponse_Price_DEFAULT
	}
	return *p.Price
}

var ProductResponse_Description_DEFAULT string

func (p *ProductResponse) GetDescription() (v string) {
	if !p.IsSetDescription() {
		return ProductResponse_Description_DEFAULT
	}
	return *p.Description
}

var ProductResponse_Status_DEFAULT int8

func (p *ProductResponse) GetStatus() (v int8) {
	if !p.IsSetStatus() {
		return ProductResponse_Status_DEFAULT
	}
	return *p.Status
}

var ProductResponse_CreateTime_DEFAULT string

func (p *ProductResponse) GetCreateTime() (v string) {
	if !p.IsSetCreateTime() {
		return ProductResponse_CreateTime_DEFAULT
	}
	return *p.CreateTime
}

var ProductResponse_StockNum_DEFAULT int32

func (p *ProductResponse) GetStockNum() (v int32) {
	if !p.IsSetStockNum() {
		return ProductResponse_StockNum_DEFAULT
	}
	return *p.StockNum
}
func (p *ProductResponse) SetId(val *int64) {
	p.Id = val
}
func (p *ProductResponse) SetProductName(val *string) {
	p.ProductName = val
}
func (p *ProductResponse) SetCategory(val *string) {
	p.Category = val
}
func (p *ProductResponse) SetPrice(val *float64) {
	p.Price = val
}
func (p *ProductResponse) SetDescription(val *string) {
	p.Description = val
}
func (p *ProductResponse) SetStatus(val *int8) {
	p.Status = val
}
func (p *ProductResponse) SetCreateTime(val *string) {
	p.CreateTime = val
}
func (p *ProductResponse) SetStockNum(val *int32) {
	p.StockNum = val
}

func (p *ProductResponse) IsSetId() bool {
	return p.Id != nil
}

func (p *ProductResponse) IsSetProductName() bool {
	return p.ProductName != nil
}

func (p *ProductResponse) IsSetCategory() bool {
	return p.Category != nil
}

func (p *ProductResponse) IsSetPrice() bool {
	return p.Price != nil
}

func (p *ProductResponse) IsSetDescription() bool {
	return p.Description != nil
}

func (p *ProductResponse) IsSetStatus() bool {
	return p.Status != nil
}

func (p *ProductResponse) IsSetCreateTime() bool {
	return p.CreateTime != nil
}

func (p *ProductResponse) IsSetStockNum() bool {
	return p.StockNum != nil
}

func (p *ProductResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductResponse(%+v)", *p)
}

var fieldIDToName_ProductResponse = map[int16]string{
	1: "id",
	2: "productName",
	3: "category",
	4: "price",
	5: "description",
	6: "status",
	7: "createTime",
	8: "stockNum",
}

type ProductException struct {
	Message string `thrift:"message,1,required" frugal:"1,required,string" json:"message"`
	Code    *int32 `thrift:"code,2,optional" frugal:"2,optional,i32" json:"code,omitempty"`
}

func NewProductException() *ProductException {
	return &ProductException{}
}

func (p *ProductException) InitDefault() {
}

func (p *ProductException) GetMessage() (v string) {
	return p.Message
}

var ProductException_Code_DEFAULT int32

func (p *ProductException) GetCode() (v int32) {
	if !p.IsSetCode() {
		return ProductException_Code_DEFAULT
	}
	return *p.Code
}
func (p *ProductException) SetMessage(val string) {
	p.Message = val
}
func (p *ProductException) SetCode(val *int32) {
	p.Code = val
}

func (p *ProductException) IsSetCode() bool {
	return p.Code != nil
}

func (p *ProductException) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductException(%+v)", *p)
}
func (p *ProductException) Error() string {
	return p.String()
}

var fieldIDToName_ProductException = map[int16]string{
	1: "message",
	2: "code",
}

type ProductService interface {
	GetProductById(ctx context.Context, request *ProductRequest) (r *ProductResponse, err error)
}

type ProductServiceGetProductByIdArgs struct {
	Request *ProductRequest `thrift:"request,1" frugal:"1,default,ProductRequest" json:"request"`
}

func NewProductServiceGetProductByIdArgs() *ProductServiceGetProductByIdArgs {
	return &ProductServiceGetProductByIdArgs{}
}

func (p *ProductServiceGetProductByIdArgs) InitDefault() {
}

var ProductServiceGetProductByIdArgs_Request_DEFAULT *ProductRequest

func (p *ProductServiceGetProductByIdArgs) GetRequest() (v *ProductRequest) {
	if !p.IsSetRequest() {
		return ProductServiceGetProductByIdArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *ProductServiceGetProductByIdArgs) SetRequest(val *ProductRequest) {
	p.Request = val
}

func (p *ProductServiceGetProductByIdArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *ProductServiceGetProductByIdArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceGetProductByIdArgs(%+v)", *p)
}

var fieldIDToName_ProductServiceGetProductByIdArgs = map[int16]string{
	1: "request",
}

type ProductServiceGetProductByIdResult struct {
	Success *ProductResponse  `thrift:"success,0,optional" frugal:"0,optional,ProductResponse" json:"success,omitempty"`
	Ex      *ProductException `thrift:"ex,1,optional" frugal:"1,optional,ProductException" json:"ex,omitempty"`
}

func NewProductServiceGetProductByIdResult() *ProductServiceGetProductByIdResult {
	return &ProductServiceGetProductByIdResult{}
}

func (p *ProductServiceGetProductByIdResult) InitDefault() {
}

var ProductServiceGetProductByIdResult_Success_DEFAULT *ProductResponse

func (p *ProductServiceGetProductByIdResult) GetSuccess() (v *ProductResponse) {
	if !p.IsSetSuccess() {
		return ProductServiceGetProductByIdResult_Success_DEFAULT
	}
	return p.Success
}

var ProductServiceGetProductByIdResult_Ex_DEFAULT *ProductException

func (p *ProductServiceGetProductByIdResult) GetEx() (v *ProductException) {
	if !p.IsSetEx() {
		return ProductServiceGetProductByIdResult_Ex_DEFAULT
	}
	return p.Ex
}
func (p *ProductServiceGetProductByIdResult) SetSuccess(x interface{}) {
	p.Success = x.(*ProductResponse)
}
func (p *ProductServiceGetProductByIdResult) SetEx(val *ProductException) {
	p.Ex = val
}

func (p *ProductServiceGetProductByIdResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ProductServiceGetProductByIdResult) IsSetEx() bool {
	return p.Ex != nil
}

func (p *ProductServiceGetProductByIdResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceGetProductByIdResult(%+v)", *p)
}

var fieldIDToName_ProductServiceGetProductByIdResult = map[int16]string{
	0: "success",
	1: "ex",
}

// exceptions of methods in ProductService.
var (
	_ error = (*ProductException)(nil)
)
