// Code generated by Kitex v0.15.2. DO NOT EDIT.

package productservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	product "shopping/product_service/server/kitex_gen/product"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"getProductById": kitex.NewMethodInfo(
		getProductByIdHandler,
		newProductServiceGetProductByIdArgs,
		newProductServiceGetProductByIdResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	productServiceServiceInfo                = NewServiceInfo()
	productServiceServiceInfoForClient       = NewServiceInfoForClient()
	productServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return productServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return productServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return productServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ProductService"
	handlerType := (*product.ProductService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "product",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func getProductByIdHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*product.ProductServiceGetProductByIdArgs)
	realResult := result.(*product.ProductServiceGetProductByIdResult)
	success, err := handler.(product.ProductService).GetProductById(ctx, realArg.Request)
	if err != nil {
		switch v := err.(type) {
		case *product.ProductException:
			realResult.Ex = v
		default:
			return err
		}
	} else {
		realResult.Success = success
	}
	return nil
}
func newProductServiceGetProductByIdArgs() interface{} {
	return product.NewProductServiceGetProductByIdArgs()
}

func newProductServiceGetProductByIdResult() interface{} {
	return product.NewProductServiceGetProductByIdResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetProductById(ctx context.Context, request *product.ProductRequest) (r *product.ProductResponse, err error) {
	var _args product.ProductServiceGetProductByIdArgs
	_args.Request = request
	var _result product.ProductServiceGetProductByIdResult
	if err = p.c.Call(ctx, "getProductById", &_args, &_result); err != nil {
		return
	}
	switch {
	case _result.Ex != nil:
		return r, _result.Ex
	}
	return _result.GetSuccess(), nil
}
